mode: 0 # 本地模式为1，腾讯云函数为0

baiduocr: #百度云识别验证码（必填）
    APP_ID : ''
    API_KEY : ''
    SECRET_KEY : ''

users: #用户基本信息（必填）
  - user:
      username: "2120171***"  #账号
      password: "" #密码
      address:  #两个地址，每次随机一个填写
      - 'xx省xx市xx区xx'
      - 'xx省xx市xx区xx'
      lon: 114.9160872 #经纬度
      lat: 25.837587

danxuan:  #单选默认填否，特殊选项在此填写
    title:
    - '今天是否在江西省内？'
    - '2'
    value: '3'
danxuanmoren: #单选默认值
  value:
    - '否'
    - '全部装备到位'
duoxuan: #多选值
  - '没有以上症状'
  - '厨房'
sort: 11 #表单总数+1


#以下为通知手段，非必须
mail: "QQ号@qq.com"#QQ邮箱地址，收发一体,没有或不用填0
mailmima: "q**********ceaej"#授权码
vxsever: 'SCU1****************************bd0b85f6862b9245a3' #微信通知，没有或不用则填0
